---
name: bump-dev-version

on:
  push:
    branches: [main]

jobs:
  bump:
    uses: Felixmil/Workflows/.github/workflows/bump_dev_version_v2.yaml@simplify-bump-dev-version-action
    with:
      workflows-ref: simplify-bump-dev-version-action
