---
name: description-manager

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  manage:
    uses: Felixmil/Workflows/.github/workflows/description_manager.yaml@simplify-bump-dev-version-action
    permissions:
      contents: write
    with:
      workflows-ref: simplify-bump-dev-version-action
